version: "3"
services:
  react:
    # platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: mern-ui
    networks:
      - mern-stack-net
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    depends_on:
      - express

  express:
    # platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    container_name: mern-api
    networks:
      - mern-stack-net
    volumes:
      - ./backend:/app
      - /app/node_modules

networks:
  mern-stack-net:
    driver: bridge
